'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidade de Salvamento Automático do My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property path() As String
            Get
                Return CType(Me("path"),String)
            End Get
            Set
                Me("path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property saida() As String
            Get
                Return CType(Me("saida"),String)
            End Get
            Set
                Me("saida") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property base() As String
            Get
                Return CType(Me("base"),String)
            End Get
            Set
                Me("base") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property acesso() As Boolean
            Get
                Return CType(Me("acesso"),Boolean)
            End Get
            Set
                Me("acesso") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property variaveis() As String
            Get
                Return CType(Me("variaveis"),String)
            End Get
            Set
                Me("variaveis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property valores() As String
            Get
                Return CType(Me("valores"),String)
            End Get
            Set
                Me("valores") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property viewerNow() As String
            Get
                Return CType(Me("viewerNow"),String)
            End Get
            Set
                Me("viewerNow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property viewerActive() As Boolean
            Get
                Return CType(Me("viewerActive"),Boolean)
            End Get
            Set
                Me("viewerActive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property objects() As String
            Get
                Return CType(Me("objects"),String)
            End Get
            Set
                Me("objects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property objectsValues() As String
            Get
                Return CType(Me("objectsValues"),String)
            End Get
            Set
                Me("objectsValues") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nunc odio, tinci"& _ 
            "dunt eu blandit nec, porta ac velit. Suspendisse potenti. Nam porttitor neque et"& _ 
            " nisi elementum, nec suscipit mauris mollis. Vestibulum quis nulla nibh. Mauris "& _ 
            "condimentum turpis id est aliquet, nec imperdiet sapien rhoncus. Nam imperdiet s"& _ 
            "emper suscipit. Curabitur placerat arcu auctor, facilisis orci a, ullamcorper sa"& _ 
            "pien. Mauris at aliquet tortor. Duis ac rutrum magna. Etiam bibendum vel sapien "& _ 
            "ut mollis. Proin tempor sed sem at volutpat. Vestibulum tincidunt quam lorem, no"& _ 
            "n facilisis sapien tincidunt vitae. Quisque condimentum gravida metus et mollis."& _ 
            " Vivamus iaculis magna magna, non placerat augue ornare id. Curabitur at neque e"& _ 
            "fficitur justo lacinia lacinia. Morbi convallis rhoncus tellus eu eleifend. Pell"& _ 
            "entesque maximus nibh et lorem pharetra, et feugiat nisi volutpat. Curabitur ut "& _ 
            "dapibus nulla. Vivamus egestas odio sed consectetur dignissim. Aenean sapien nib"& _ 
            "h, porttitor a nisi vitae, tempor finibus erat. Fusce finibus libero nec sceleri"& _ 
            "sque commodo. Vestibulum vestibulum mi lacus, nec dapibus dui bibendum sit amet."& _ 
            " Mauris vitae nibh arcu. Sed placerat venenatis efficitur. Curabitur molestie, o"& _ 
            "dio eget porta imperdiet, diam magna rutrum turpis, in feugiat dolor ante in tel"& _ 
            "lus. Nulla tellus ex, condimentum sed laoreet nec, sagittis ut arcu. Mauris cong"& _ 
            "ue est diam, eu convallis nulla consequat nec. Integer elementum ex sapien, sed "& _ 
            "lacinia quam venenatis maximus. Cras fermentum, libero ac auctor congue, urna fe"& _ 
            "lis faucibus sem, id viverra sem nisi commodo enim. Duis scelerisque blandit orc"& _ 
            "i id euismod. In tincidunt mauris at auctor egestas. Sed nec justo quis felis fa"& _ 
            "ucibus scelerisque. Suspendisse consequat nec quam sed mattis. Sed pretium mi ni"& _ 
            "si, quis gravida eros efficitur quis. Nunc sed mollis nibh. Pellentesque rutrum "& _ 
            "tempus molestie. Nullam bibendum lobortis dui in consequat. Cras interdum ligula"& _ 
            " eu ornare commodo. Nunc dictum interdum auctor. Nunc eget elit eu nisi convalli"& _ 
            "s interdum. Cras placerat dui sit amet mauris scelerisque dignissim. Cras molest"& _ 
            "ie mi sed posuere sagittis. Donec commodo est nulla. Nullam pretium congue nisi "& _ 
            "sit amet mattis. Donec sit amet nulla a elit lobortis scelerisque nec quis mauri"& _ 
            "s. Fusce feugiat metus a purus lacinia iaculis. Lorem ipsum dolor sit amet, cons"& _ 
            "ectetur adipiscing elit. Nulla pretium, risus vestibulum sollicitudin aliquet, l"& _ 
            "igula nisi ullamcorper nisi, in fringilla orci dolor vitae nisi. Nunc euismod ve"& _ 
            "hicula quam, eu condimentum lacus malesuada sed. Integer hendrerit porta sapien,"& _ 
            " non tincidunt mauris. Nunc luctus erat vitae tortor tempor vehicula. Sed nisl v"& _ 
            "elit, gravida vitae pretium quis, interdum vitae purus. Nam in dolor condimentum"& _ 
            " nisi vestibulum fringilla in ac risus. Quisque cursus dolor vel dui aliquet, ve"& _ 
            "l suscipit augue egestas. Sed id rutrum lacus. Nam justo ante, lacinia eget magn"& _ 
            "a at, pharetra vehicula orci. Aliquam tincidunt vitae nunc dignissim consectetur"& _ 
            ". Aliquam tincidunt tempus elit, sed vestibulum mauris scelerisque ac. Nunc eu v"& _ 
            "olutpat elit. Donec fermentum mattis velit in fermentum. Cras congue tortor vita"& _ 
            "e volutpat tristique. Nam libero nulla, convallis id tortor eu, finibus posuere "& _ 
            "mi. Nam blandit bibendum magna, sit amet elementum est venenatis vitae. Maecenas"& _ 
            " velit lectus, luctus elementum metus sit amet, posuere maximus elit. In hac hab"& _ 
            "itasse platea dictumst. Curabitur vestibulum justo eget velit tristique convalli"& _ 
            "s. Maecenas vestibulum tortor ipsum, vel condimentum velit pretium id. Curabitur"& _ 
            " lacinia ipsum id dapibus mollis. Mauris erat mauris, volutpat molestie turpis v"& _ 
            "itae, laoreet vulputate mauris. Morbi vitae velit quis leo bibendum dignissim ut"& _ 
            " at elit. In aliquam orci semper faucibus commodo. Mauris sit amet vestibulum ni"& _ 
            "sl, in pulvinar ligula. Phasellus quis ullamcorper justo. Aenean a gravida lectu"& _ 
            "s, id ultrices lorem. Praesent ultricies egestas enim sit amet auctor. Curabitur"& _ 
            " feugiat in tellus vitae pulvinar. Aliquam maximus, justo sit amet condimentum s"& _ 
            "odales, nibh risus venenatis eros, vel ullamcorper mauris neque quis urna. Aliqu"& _ 
            "am erat volutpat. Mauris eu odio id dolor blandit consequat non vitae metus. Mor"& _ 
            "bi ut metus egestas, mollis lorem eget, laoreet enim. Nulla facilisi. Pellentesq"& _ 
            "ue convallis orci at purus semper sodales. Donec sed dui nibh. Cras consectetur "& _ 
            "risus eget tortor tempor feugiat. Nam bibendum est vitae ante interdum, imperdie"& _ 
            "t aliquam massa tincidunt. Pellentesque consequat nulla sagittis aliquet porttit"& _ 
            "or. In commodo efficitur erat, eget porta metus volutpat vel. Donec massa nisl, "& _ 
            "laoreet sed metus eget, efficitur gravida nibh. Class aptent taciti sociosqu ad "& _ 
            "litora torquent per conubia nostra, per inceptos himenaeos. Morbi elementum ligu"& _ 
            "la porta consequat convallis. Nam pulvinar rutrum ullamcorper. Integer eu accums"& _ 
            "an leo. Nunc sed arcu gravida, ornare ante sed, lobortis lacus. Aenean blandit l"& _ 
            "ectus a leo pretium varius. Aenean eu tincidunt libero, quis egestas ligula. Int"& _ 
            "eger sit amet turpis turpis. Aenean aliquam sapien vel feugiat congue. Duis tris"& _ 
            "tique lacinia lorem sit amet tincidunt. Cras pellentesque consequat urna, id mat"& _ 
            "tis metus lacinia at. Maecenas elementum eu risus eu vestibulum. Morbi sed digni"& _ 
            "ssim leo. Fusce odio ex, blandit eget nulla ac, dignissim viverra dui. Aliquam q"& _ 
            "uis metus nec erat dapibus fermentum in a eros. Aenean ultricies suscipit sem, s"& _ 
            "it amet tincidunt nisl faucibus vitae. Etiam ut ligula velit. Curabitur tincidun"& _ 
            "t rutrum sem sit amet auctor. Etiam elementum metus at consequat fermentum. Sed "& _ 
            "luctus mi in ullamcorper rutrum. Nulla facilisi. Quisque et mauris quis orci fau"& _ 
            "cibus luctus sit amet ut justo. Fusce cursus scelerisque accumsan. Nullam vestib"& _ 
            "ulum, nibh eget vehicula vehicula, ligula ex porta lectus, id finibus urna nibh "& _ 
            "ac eros. Nam fermentum odio ut lectus porttitor, vel sodales sem elementum. Phas"& _ 
            "ellus sed tellus tincidunt odio imperdiet convallis vitae ut nunc. Nullam feugia"& _ 
            "t arcu nec ante mattis, et molestie risus commodo. Nam et sapien ligula. Nam non"& _ 
            " sapien congue mi venenatis congue. Pellentesque est ipsum, pulvinar non augue a"& _ 
            ", tempus efficitur lacus. Donec fringilla lectus turpis, ac condimentum diam lac"& _ 
            "inia a. Maecenas lacinia enim in tempus fermentum. Quisque euismod massa vitae m"& _ 
            "i tristique ornare. Cras mattis neque in mi facilisis, ac ornare purus mollis. D"& _ 
            "onec pharetra massa nec ipsum porta, non sodales velit tempus. Sed elit nunc, fa"& _ 
            "cilisis quis mauris eu, congue euismod dui. Sed mattis placerat arcu non semper."& _ 
            " Ut rhoncus in sem at pulvinar. Maecenas ullamcorper, sapien vitae laoreet biben"& _ 
            "dum, massa sapien commodo urna, in efficitur purus risus quis mi. Maecenas eu ni"& _ 
            "si vitae nunc molestie euismod pharetra quis massa. Maecenas tempor cursus eros,"& _ 
            " vitae aliquet erat pharetra a. Nunc gravida vitae elit sit amet accumsan. Vesti"& _ 
            "bulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cura"& _ 
            "e; Nulla dapibus suscipit ultricies. Donec gravida nisi in sapien porttitor, et "& _ 
            "elementum mauris lobortis. Nullam malesuada, nulla eget tempus pulvinar, dolor l"& _ 
            "acus accumsan nunc, vel euismod ligula nunc pretium purus. Quisque quis lectus t"& _ 
            "ortor. Vestibulum tincidunt maximus mauris sit amet ornare. Fusce placerat sem s"& _ 
            "ed leo volutpat, et posuere orci dapibus. Etiam vehicula molestie nisl, nec vest"& _ 
            "ibulum orci posuere ut. Pellentesque in orci at sem imperdiet laoreet sit amet e"& _ 
            "u lectus. Aliquam nec lacus accumsan, dictum nisi eu, varius nibh. Donec varius "& _ 
            "diam blandit purus accumsan aliquet. Ut sit amet quam nec purus feugiat auctor e"& _ 
            "t id tortor. Cras at sem tempus, ultrices erat vel, ullamcorper ante. Fusce id c"& _ 
            "onvallis massa. Donec lacinia augue nec neque vehicula, vel laoreet libero place"& _ 
            "rat. Morbi ante nunc, malesuada id dictum hendrerit, consequat cursus nulla. Cur"& _ 
            "abitur tellus libero, iaculis ut justo vitae, tincidunt tincidunt libero. In gra"& _ 
            "vida convallis ipsum fringilla semper. Vivamus lectus eros, ullamcorper et ullam"& _ 
            "corper eu, scelerisque id mi. Morbi enim libero, sagittis eu mollis in, euismod "& _ 
            "vel lacus. Nullam lacinia accumsan semper. Proin lobortis felis sit amet libero "& _ 
            "malesuada gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultri"& _ 
            "ces posuere cubilia Curae; Aliquam nec feugiat arcu, et consequat sapien. Nulla "& _ 
            "posuere nibh sem, at facilisis ex auctor et. Proin ac enim vehicula, posuere dol"& _ 
            "or accumsan, facilisis massa. Duis at enim dui. In lobortis porta semper. Nam vu"& _ 
            "lputate tortor nec sollicitudin semper. Nunc gravida vel lectus sed dapibus. Cur"& _ 
            "abitur diam lectus, molestie vestibulum diam in, maximus congue lacus. Proin at "& _ 
            "turpis risus. Pellentesque porttitor faucibus mi ac dictum. Donec neque diam, eg"& _ 
            "estas nec purus vehicula, gravida ornare mi. Mauris ac pretium tellus, at euismo"& _ 
            "d libero. Aliquam aliquam enim viverra felis bibendum, vel scelerisque lorem ult"& _ 
            "rices. Morbi dignissim nec dui id convallis. Nulla non quam imperdiet justo rutr"& _ 
            "um imperdiet. Nam in magna bibendum, gravida ante ut, accumsan nunc. Donec tinci"& _ 
            "dunt nibh nec lacus mattis, sed pulvinar mauris ultricies. Vivamus dictum magna "& _ 
            "sit amet libero condimentum, non lobortis enim vehicula. Donec lacinia molestie "& _ 
            "ante at fringilla. Praesent ut imperdiet erat. Etiam urna turpis, vulputate dict"& _ 
            "um gravida at, interdum feugiat urna. Morbi rhoncus arcu ultrices libero sollici"& _ 
            "tudin, in malesuada odio dictum. Nunc ut malesuada sapien, sit amet condimentum "& _ 
            "lacus. In vulputate erat sapien, sed molestie nisi tempor in. Phasellus quis tor"& _ 
            "tor bibendum, dignissim quam nec, efficitur tortor. Sed iaculis quam tellus. Nul"& _ 
            "lam porta pharetra efficitur. Phasellus in erat pulvinar, viverra sem in, hendre"& _ 
            "rit massa. Integer malesuada tempus sodales. Pellentesque nec velit quis tortor "& _ 
            "feugiat luctus et eget urna. Curabitur vel consequat massa. Quisque bibendum dui"& _ 
            " ornare erat scelerisque volutpat. Pellentesque eget tortor sit amet turpis aliq"& _ 
            "uet imperdiet. Integer sed tortor efficitur, eleifend magna pretium, bibendum li"& _ 
            "gula. Donec eget lorem et enim mattis ullamcorper eu et urna. Integer molestie c"& _ 
            "onsequat justo sit amet cursus. Nulla sed facilisis mi, vitae volutpat libero. I"& _ 
            "nteger porta nulla ac magna congue finibus et a nunc. Mauris varius, velit eget "& _ 
            "sagittis iaculis, lectus nunc tincidunt nisl, non fringilla tellus ante eu justo"& _ 
            ". Integer auctor, felis at pulvinar tincidunt, elit lectus scelerisque dui, vita"& _ 
            "e tristique orci orci vitae mi. Cras pellentesque et nulla sit amet pulvinar. Pr"& _ 
            "aesent ornare placerat leo eu pharetra. Suspendisse malesuada egestas eros non e"& _ 
            "fficitur. Ut molestie erat non orci molestie vehicula. Nulla sed dolor sit amet "& _ 
            "enim aliquet ornare. In rutrum, libero at euismod ultrices, quam elit tempus nul"& _ 
            "la, convallis tristique enim mauris sed tellus. Donec varius quam pulvinar condi"& _ 
            "mentum finibus. Nunc a elit dictum, condimentum velit quis, rhoncus libero. Vest"& _ 
            "ibulum varius ultricies erat, ac vulputate orci viverra non. Ut ultricies erat s"& _ 
            "ed arcu auctor, id vehicula lorem porttitor. Sed vitae massa sit amet dolor posu"& _ 
            "ere tincidunt eu ut sapien. Maecenas condimentum ante vitae tellus tincidunt, eg"& _ 
            "et scelerisque eros cursus. Sed sed urna vitae magna congue dapibus. Phasellus f"& _ 
            "acilisis condimentum commodo. Fusce viverra lacus sit amet massa ullamcorper ege"& _ 
            "stas. Aenean at urna quis ipsum mollis viverra. Nulla diam leo, cursus eu purus "& _ 
            "et, iaculis finibus est. Suspendisse sagittis velit in elit dignissim consequat."& _ 
            " Suspendisse fringilla venenatis massa, vel faucibus diam pellentesque nec. Phas"& _ 
            "ellus scelerisque nisl egestas lorem molestie pharetra. Integer consequat quis d"& _ 
            "ui eu lobortis. Praesent venenatis sed orci ac fermentum. Aenean malesuada, odio"& _ 
            " vel elementum efficitur, augue ligula fringilla lacus, sed vehicula ante ex sed"& _ 
            " velit. Pellentesque mattis non odio id lobortis. Donec elementum nisi quis mi m"& _ 
            "olestie, eget tempus nisi porttitor. Donec eget placerat massa. Sed accumsan var"& _ 
            "ius mi, ac tempus nisi lobortis non. Sed fermentum porttitor dignissim. Quisque "& _ 
            "lacinia justo a justo porta, ut ornare dui luctus. Sed suscipit consequat tempus"& _ 
            ". Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et convallis "& _ 
            "erat. Aliquam ac lacus mollis, posuere tellus sed, congue est. Nulla facilisi. D"& _ 
            "uis vitae odio consectetur, maximus neque eget, ultrices lorem. Nunc semper turp"& _ 
            "is nec vestibulum sodales. Nulla et felis vel dui tristique efficitur. Cras in d"& _ 
            "ui metus. Suspendisse aliquet, leo ut finibus condimentum, lectus est consectetu"& _ 
            "r massa, eget tristique ex felis quis tortor. Vivamus tristique vitae urna a pre"& _ 
            "tium. Mauris at lectus facilisis eros blandit euismod. Donec consectetur lorem d"& _ 
            "olor, et feugiat diam condimentum a. Aenean et convallis nulla. Duis vel mi nec "& _ 
            "turpis auctor dignissim. Cras et tortor vitae lectus malesuada scelerisque sed p"& _ 
            "haretra nunc. Nam dignissim, purus vel sollicitudin vestibulum, orci neque sagit"& _ 
            "tis augue, ac imperdiet arcu enim eu purus. Pellentesque vel nibh et diam maximu"& _ 
            "s tempus. Aenean viverra dapibus tempus. Morbi vulputate elit arcu, in pretium a"& _ 
            "nte tristique sed. Fusce in posuere augue. Nulla ut sem eu est venenatis porttit"& _ 
            "or. Cras eleifend odio et urna bibendum, vel fringilla nulla tempor. Fusce variu"& _ 
            "s dapibus libero, facilisis viverra tortor laoreet et. Fusce viverra sed ante se"& _ 
            "d placerat. Praesent fringilla, lacus ut luctus mattis, erat nisi iaculis purus,"& _ 
            " at viverra lectus ante in felis. Praesent maximus sagittis nisi id aliquet. Don"& _ 
            "ec vel consequat odio. Sed ac nibh quis nisi molestie dictum. Sed sagittis nibh "& _ 
            "efficitur, malesuada odio at, blandit orci. Vestibulum sagittis, nisl ut hendrer"& _ 
            "it blandit, quam urna condimentum erat, sed dignissim lacus enim quis enim. Viva"& _ 
            "mus nec est ac lacus tincidunt consectetur et ac sem. Pellentesque eu efficitur "& _ 
            "nunc, id semper tortor. Quisque vel ornare metus. In hac habitasse platea dictum"& _ 
            "st. Sed et quam vulputate, luctus neque ut, iaculis diam. Nam nunc odio, suscipi"& _ 
            "t in massa et, scelerisque ullamcorper enim. In magna lorem, dignissim eu feugia"& _ 
            "t nec, aliquet sit amet erat. Class aptent taciti sociosqu ad litora torquent pe"& _ 
            "r conubia nostra, per inceptos himenaeos. Donec dictum fermentum nibh, in interd"& _ 
            "um lorem dignissim vel. Pellentesque habitant morbi tristique senectus et netus "& _ 
            "et malesuada fames ac turpis egestas. Integer non diam bibendum metus sagittis m"& _ 
            "ollis quis vitae eros. Ut dictum condimentum nunc eget posuere. Mauris vitae mas"& _ 
            "sa ut est interdum hendrerit sed ut massa. Mauris eu ultricies dolor. Nullam et "& _ 
            "laoreet massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a "& _ 
            "risus ac felis molestie interdum. Nunc consectetur ac dui sit amet ornare. Curab"& _ 
            "itur at ex rutrum, vehicula mauris eget, condimentum lectus. Mauris nulla nisl, "& _ 
            "porttitor non dui ut, condimentum rutrum sem. Nunc auctor augue eget ex tempus, "& _ 
            "in luctus felis faucibus. Maecenas risus orci, rutrum quis lacinia eu, eleifend "& _ 
            "id sem. Donec eleifend purus tortor, ac dapibus massa sodales vestibulum. Pellen"& _ 
            "tesque venenatis risus et quam efficitur tincidunt. Aliquam erat volutpat. Maece"& _ 
            "nas dapibus eget urna sit amet pellentesque. Suspendisse a justo at ligula rutru"& _ 
            "m luctus. Nullam eget tempus metus. Nullam in luctus metus, ut elementum mi. Sus"& _ 
            "pendisse efficitur volutpat lacinia. Nulla sed fermentum turpis. Pellentesque su"& _ 
            "scipit nulla eu aliquam condimentum. Aenean volutpat eros dictum rhoncus dapibus"& _ 
            ". Proin nec ante quis mi mollis volutpat. Curabitur at eros leo. Sed sit amet au"& _ 
            "ctor purus. Sed a mauris libero. Etiam ullamcorper lacus et turpis pharetra port"& _ 
            "titor. Ut tempus placerat sagittis. Aliquam a placerat mauris. Duis dictum, tort"& _ 
            "or non varius viverra, urna lacus lacinia elit, et elementum mauris purus eu vel"& _ 
            "it. Proin quis fermentum lacus, ut dictum nunc. Praesent eu lobortis elit, ut eu"& _ 
            "ismod nulla. Vivamus in nunc eget ipsum sagittis finibus in non neque. Praesent "& _ 
            "vel erat a metus laoreet condimentum. Aenean non tristique est, id maximus ligul"& _ 
            "a. Quisque in blandit ex. Donec tincidunt neque magna. Sed non diam faucibus, or"& _ 
            "nare magna sed, feugiat est. Phasellus ac ex est. Curabitur congue magna ut lobo"& _ 
            "rtis faucibus. In mattis ante tortor, a lacinia odio hendrerit in. Sed bibendum "& _ 
            "finibus dui, at finibus nisl feugiat eu. Sed leo nunc, pellentesque ac quam non,"& _ 
            " laoreet semper mauris. Nunc congue, tellus in finibus egestas, velit tortor con"& _ 
            "gue enim, vel rhoncus ante nunc at eros. Ut in lacinia tellus, nec porttitor nib"& _ 
            "h. Aenean eu dignissim neque, eget convallis tellus. Curabitur varius nulla nec "& _ 
            "nulla malesuada, ut rhoncus mauris placerat. Praesent quis libero vitae ligula l"& _ 
            "aoreet dictum quis ut odio. Mauris dictum laoreet elit, in imperdiet ligula vest"& _ 
            "ibulum maximus. In lobortis at augue id tempus. Donec a cursus orci, a pulvinar "& _ 
            "mi. Aenean tincidunt elit quis bibendum euismod. Maecenas nec efficitur felis. C"& _ 
            "ras volutpat nisi arcu, eget tempor felis laoreet id. Vivamus ut tortor eros. Na"& _ 
            "m maximus pellentesque mauris, id mollis erat rutrum sed. Morbi sapien ligula, f"& _ 
            "inibus ut gravida sit amet, fringilla vel tortor. In hac habitasse platea dictum"& _ 
            "st. Duis volutpat ultricies leo, et semper neque laoreet nec. Duis tempus nunc e"& _ 
            "get vulputate mattis. Sed quam leo, hendrerit vel varius at, dictum eget odio. P"& _ 
            "roin eget pretium quam. Nullam eleifend lectus id urna tincidunt venenatis. Pell"& _ 
            "entesque congue nunc at magna gravida bibendum. Nulla aliquet metus quis facilis"& _ 
            "is ultrices. Quisque consequat lorem diam, ut laoreet magna molestie vel. Quisqu"& _ 
            "e non lacus est. Nam lobortis in arcu eu feugiat. Nam vitae eleifend leo. Pellen"& _ 
            "tesque nunc nulla, facilisis at pellentesque in, porta ac nulla. Aliquam pulvina"& _ 
            "r sapien vel nisi maximus, sit amet accumsan purus iaculis. Suspendisse non enim"& _ 
            " ultricies, rutrum ligula sed, ullamcorper mauris. Integer erat odio, porta a pe"& _ 
            "llentesque et, lacinia sit amet neque. Curabitur ullamcorper sem sit amet eros l"& _ 
            "uctus dapibus. Nulla at lorem vitae ipsum ullamcorper convallis. Suspendisse sce"& _ 
            "lerisque sed orci ac mollis. Suspendisse potenti. Duis cursus ex neque. Aenean n"& _ 
            "on velit ac neque euismod lacinia. Curabitur eleifend ligula eget neque vehicula"& _ 
            ", in porta tellus venenatis. Nunc laoreet orci non sem consectetur, sed lobortis"& _ 
            " urna suscipit. Integer in purus at ante pellentesque sollicitudin a vitae tellu"& _ 
            "s. Phasellus cursus enim sit amet massa ornare, in lacinia turpis pretium. Curab"& _ 
            "itur condimentum convallis tellus et mattis. Fusce urna diam, tincidunt convalli"& _ 
            "s ligula non, pulvinar condimentum tellus. Fusce eros nulla, scelerisque vel urn"& _ 
            "a quis, laoreet porta lectus. Vestibulum bibendum semper nibh, vitae sagittis au"& _ 
            "gue maximus eu. Integer lacinia sapien quis justo sagittis, in tempus sem eleife"& _ 
            "nd. Nullam vitae commodo mi. Praesent commodo imperdiet fermentum. Phasellus veh"& _ 
            "icula metus id velit vulputate rhoncus. Vestibulum sodales, magna nec mollis pha"& _ 
            "retra, sapien dui dapibus mi, eu porta ex quam vel tortor. Pellentesque vel pell"& _ 
            "entesque libero. Quisque varius ante eleifend lacus consequat finibus. Vivamus v"& _ 
            "ulputate, ex eu molestie facilisis, ex risus varius augue, at auctor mi ante vel"& _ 
            " diam. Nullam vulputate nisl justo. Nulla bibendum dui at orci scelerisque, at u"& _ 
            "ltrices ipsum consequat. Nunc erat felis, ultricies eget enim eu, porttitor accu"& _ 
            "msan purus. Phasellus sed consectetur massa. Sed mollis consequat est. Proin non"& _ 
            " erat non nulla pretium laoreet. Nulla porta, risus et ultricies convallis, risu"& _ 
            "s dui imperdiet dolor, in ornare nisl augue ut nisl. Aliquam dictum tempus nisi "& _ 
            "lobortis tempus. Etiam consectetur non nunc in condimentum. Cras ac malesuada ve"& _ 
            "lit. Cras congue finibus turpis eu lacinia. Integer pellentesque lacinia tincidu"& _ 
            "nt. In tempus rhoncus laoreet. Integer scelerisque vehicula odio a auctor. In tr"& _ 
            "istique nec massa a gravida. Maecenas venenatis, velit eu pharetra mattis, orci "& _ 
            "lectus feugiat ipsum, in bibendum odio sapien nec erat. Cras placerat, elit vel "& _ 
            "pretium malesuada, orci justo luctus nulla, sit amet pretium urna turpis nec eni"& _ 
            "m. Vivamus tempus sit amet dui ut tincidunt. Integer et sapien vehicula, porttit"& _ 
            "or lorem vel, tempor ante. Duis interdum libero quis augue vulputate pulvinar. E"& _ 
            "tiam ut lorem purus. Ut at laoreet tellus. Proin mollis euismod sem, ut pulvinar"& _ 
            " ipsum auctor eu. Nunc sed sem enim. Donec neque ante, finibus ac purus at, soll"& _ 
            "icitudin eleifend nunc. Vivamus suscipit ex vel lorem accumsan, ut consectetur m"& _ 
            "auris porttitor. Donec bibendum lectus non nulla.")>  _
        Public Property lorem() As String
            Get
                Return CType(Me("lorem"),String)
            End Get
            Set
                Me("lorem") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.block_compiler.My.MySettings
            Get
                Return Global.block_compiler.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
